/**
 * GitHub API compatibility shim — barrel exports.
 *
 * @module
 */

export { handleShimRequest, startShimServer } from './server.js';
export type { ShimServerOptions } from './server.js';

export {
  handleCancelWorkflowRun,
  handleCreateOrUpdateEnvironmentSecret,
  handleCreateOrUpdateRepositorySecret,
  handleCreateEnvironmentVariable,
  handleCreateRepositoryVariable,
  handleCreateWorkflowDispatch,
  handleDeleteActionsCacheById,
  handleDeleteActionsCachesByKey,
  handleDeleteArtifact,
  handleDeleteEnvironmentSecret,
  handleDeleteEnvironmentVariable,
  handleDeleteRepositorySecret,
  handleDeleteRepositoryVariable,
  handleDeleteWorkflowRun,
  handleDeleteWorkflowRunLogs,
  handleDisableWorkflow,
  handleDownloadArtifact,
  handleDownloadWorkflowRunAttemptLogs,
  handleDownloadWorkflowJobLogs,
  handleDownloadWorkflowRunLogs,
  handleEnableWorkflow,
  handleForceCancelWorkflowRun,
  handleGetActionsCacheRetentionLimit,
  handleGetActionsCacheStorageLimit,
  handleGetActionsCacheUsage,
  handleGetActionsPermissions,
  handleGetActionsSelectedActions,
  handleGetActionsWorkflowPermissions,
  handleGetArtifact,
  handleGetEnvironmentSecret,
  handleGetEnvironmentSecretsPublicKey,
  handleGetEnvironmentVariable,
  handleGetRepositorySecret,
  handleGetRepositorySecretsPublicKey,
  handleGetRepositoryVariable,
  handleGetWorkflow,
  handleGetWorkflowJob,
  handleGetWorkflowRun,
  handleGetWorkflowRunAttempt,
  handleGetWorkflowRunUsage,
  handleGetWorkflowUsage,
  handleListArtifacts,
  handleListActionsCaches,
  handleListEnvironmentSecrets,
  handleListEnvironmentVariables,
  handleListRepositorySecrets,
  handleListRepositoryVariables,
  handleListWorkflowRunArtifacts,
  handleListWorkflowRunJobs,
  handleListWorkflowRuns,
  handleListWorkflowRunsForWorkflow,
  handleListWorkflows,
  handleRerunFailedWorkflowJobs,
  handleRerunWorkflowJob,
  handleRerunWorkflowRun,
  handleSetActionsCacheRetentionLimit,
  handleSetActionsCacheStorageLimit,
  handleSetActionsPermissions,
  handleSetActionsSelectedActions,
  handleSetActionsWorkflowPermissions,
  handleUpdateEnvironmentVariable,
  handleUpdateRepositoryVariable,
} from './actions.js';
export { handleListPublicEvents, handleListReceivedEvents, handleListRepoActivity, handleListRepoEvents, handleListUserEvents } from './activity.js';
export { handleCreateCommitComment, handleCreateCommitCommentReaction, handleDeleteCommitComment, handleDeleteCommitCommentReaction, handleGetCommitComment, handleListCommitCommentReactions, handleListCommitComments, handleListCommitCommentsForSha, handleUpdateCommitComment } from './commit-comments.js';
export { handleGetContents, handleGetLicense, handleGetRawContent, handleGetReadme, handleGetReadmeInDirectory } from './contents.js';
export { handleCreateDeployment, handleCreateDeploymentStatus, handleCreateOrUpdateEnvironment, handleDeleteDeployment, handleDeleteEnvironment, handleGetDeployment, handleGetDeploymentStatus, handleGetEnvironment, handleListDeployments, handleListDeploymentStatuses, handleListEnvironments } from './deployments.js';
export { handleAddAuthenticatedEmails, handleDeleteAuthenticatedEmails, handleListAuthenticatedEmails, handleListAuthenticatedPublicEmails, handleSetPrimaryEmailVisibility } from './emails.js';
export { handleBlockUser, handleCheckBlockedUser, handleCheckFollowing, handleFollowUser, handleListBlockedUsers, handleListFollowers, handleListFollowing, handleUnblockUser, handleUnfollowUser } from './follows.js';
export { handleCheckGistStar, handleCreateGist, handleCreateGistComment, handleDeleteGist, handleDeleteGistComment, handleForkGist, handleGetGist, handleGetGistComment, handleGetGistRawFile, handleGetGistRevision, handleListAuthenticatedGists, handleListGistComments, handleListGistCommits, handleListGistForks, handleListPublicGists, handleListStarredGists, handleListUserGists, handleStarGist, handleUnstarGist, handleUpdateGist, handleUpdateGistComment } from './gists.js';
export { handleCreateAuthenticatedGpgKey, handleDeleteAuthenticatedGpgKey, handleGetAuthenticatedGpgKey, handleListAuthenticatedGpgKeys, handleListUserGpgKeys } from './gpg-keys.js';
export { handleAddAuthenticatedSocialAccounts, handleDeleteAuthenticatedSocialAccounts, handleListAuthenticatedSocialAccounts, handleListUserSocialAccounts } from './social-accounts.js';
export { handleCreateAuthenticatedSshKey, handleDeleteAuthenticatedSshKey, handleGetAuthenticatedSshKey, handleListAuthenticatedSshKeys, handleListUserSshKeys } from './user-keys.js';
export { handleCreateAuthenticatedSshSigningKey, handleDeleteAuthenticatedSshSigningKey, handleGetAuthenticatedSshSigningKey, handleListAuthenticatedSshSigningKeys, handleListUserSshSigningKeys } from './user-keys.js';
export { handleCancelPagesDeployment, handleCreatePagesDeployment, handleCreatePagesSite, handleDeletePagesSite, handleGetLatestPagesBuild, handleGetPagesBuild, handleGetPagesDeploymentStatus, handleGetPagesHealth, handleGetPagesSite, handleListPagesBuilds, handleRequestPagesBuild, handleUpdatePagesSite } from './pages.js';
export { handleGetCommunityProfile, handleGetStatsCodeFrequency, handleGetStatsCommitActivity, handleGetStatsContributors, handleGetStatsParticipation, handleGetStatsPunchCard, handleGetTrafficClones, handleGetTrafficPopularPaths, handleGetTrafficPopularReferrers, handleGetTrafficViews } from './metrics.js';
export {
  handleAddOrgTeamMembership,
  handleAddOrgTeamMembershipById,
  handleAddOrUpdateOrgTeamRepo,
  handleAddOrUpdateOrgTeamRepoById,
  handleAddOrUpdateTeamRepoById,
  handleAddTeamMembershipById,
  handleBlockOrgUser,
  handleCancelOrgInvitation,
  handleCheckOrgBlockedUser,
  handleCheckOrgMember,
  handleCheckOrgTeamMember,
  handleCheckOrgTeamRepo,
  handleCheckOrgTeamRepoById,
  handleCheckPublicOrgMember,
  handleCheckTeamMemberById,
  handleCheckTeamRepoById,
  handleDeleteOrgCustomProperty,
  handleCreateOrgIssueField,
  handleCreateOrgIssueType,
  handleCreateOrgRepo,
  handleCreateOrgTeam,
  handleConvertOrgMemberToOutsideCollaborator,
  handleDeleteOrgIssueField,
  handleDeleteOrgIssueType,
  handleDeleteOrgTeam,
  handleDeleteOrgTeamById,
  handleDeleteTeamById,
  handleGetAuthenticatedOrgMembership,
  handleGetOrg,
  handleGetOrgCustomProperty,
  handleGetOrgMembership,
  handleGetOrgTeam,
  handleGetOrgTeamById,
  handleGetOrgTeamMembership,
  handleGetOrgTeamMembershipById,
  handleGetTeamById,
  handleGetTeamMembershipById,
  handleListAuthenticatedOrgMemberships,
  handleListAuthenticatedOrgs,
  handleListAuthenticatedUserTeams,
  handleListFailedOrgInvitations,
  handleListOrganizations,
  handleListOrgBlockedUsers,
  handleListOrgCustomProperties,
  handleListOrgCustomPropertyValues,
  handleListOrgInvitationTeams,
  handleListOrgInvitations,
  handleListOrgIssueFields,
  handleListOrgIssueTypes,
  handleListOrgMembers,
  handleListOrgRepos,
  handleListOrgTeamChildTeams,
  handleListOrgTeamChildTeamsById,
  handleListOrgTeamInvitations,
  handleListOrgTeamInvitationsById,
  handleListOrgTeamMembers,
  handleListOrgTeamMembersById,
  handleListOrgTeamRepos,
  handleListOrgTeamReposById,
  handleListOrgTeams,
  handleListOutsideCollaborators,
  handleListRepoTeams,
  handleListTeamChildTeamsById,
  handleListTeamInvitationsById,
  handleListTeamMembersById,
  handleListTeamReposById,
  handleListUserOrgs,
  handleRemoveOrgMembership,
  handleRemoveOrgTeamMembership,
  handleRemoveOrgTeamMembershipById,
  handleRemoveOrgTeamRepo,
  handleRemoveOrgTeamRepoById,
  handleRemoveOutsideCollaborator,
  handleRemovePublicOrgMembership,
  handleRemoveTeamMembershipById,
  handleRemoveTeamRepoById,
  handleSetOrgMembership,
  handleSetPublicOrgMembership,
  handleUnblockOrgUser,
  handleUpdateAuthenticatedOrgMembership,
  handleUpdateOrg,
  handlePutOrgCustomProperty,
  handleUpdateOrgCustomPropertyValues,
  handleUpdateOrgIssueField,
  handleUpdateOrgIssueType,
  handleUpdateOrgTeam,
  handleUpdateOrgTeamById,
  handleUpsertOrgCustomProperties,
  handleUpdateTeamById,
} from './orgs.js';
export {
  buildRepoResponse,
  createRepoForOwner,
  handleCreateFork,
  handleCreateUserRepo,
  handleDeleteRepo,
  handleGenerateRepoFromTemplate,
  handleGetRepo,
  handleListAuthenticatedRepos,
  handleListForks,
  handleListPublicRepositories,
  handleListRepos,
  handleListUserRepos,
  handleTransferRepo,
  handleUpdateRepo,
} from './repos.js';
export {
  handleAddIssueAssignees,
  handleAddIssueLabels,
  handleCreateIssue,
  handleCreateIssueComment,
  handleCreateIssueCommentReaction,
  handleCreateIssueReaction,
  handleCreateMilestone,
  handleCreateRepoLabel,
  handleDeleteIssueComment,
  handleDeleteIssueCommentReaction,
  handleDeleteIssueReaction,
  handleDeleteMilestone,
  handleDeleteRepoLabel,
  handleGetIssue,
  handleGetIssueComment,
  handleGetIssueEvent,
  handleGetMilestone,
  handleGetRepoLabel,
  handleListAssignedIssues,
  handleListAuthenticatedUserIssues,
  handleListIssueCommentReactions,
  handleListIssueComments,
  handleListIssueEvents,
  handleListIssueLabels,
  handleListIssueReactions,
  handleListIssues,
  handleListIssueTimeline,
  handleListMilestoneLabels,
  handleListMilestones,
  handleListOrgIssues,
  handleListRepoIssueComments,
  handleListRepoIssueEvents,
  handleListRepoLabels,
  handleLockIssue,
  handlePinIssueComment,
  handleRemoveAllIssueLabels,
  handleRemoveIssueAssignees,
  handleRemoveIssueLabel,
  handleReplaceIssueLabels,
  handleUnlockIssue,
  handleUnpinIssueComment,
  handleUpdateIssue,
  handleUpdateIssueComment,
  handleUpdateMilestone,
  handleUpdateRepoLabel,
} from './issues.js';
export {
  handleCheckPullMerged,
  handleCreatePull,
  handleCreatePullReview,
  handleCreatePullReviewComment,
  handleCreatePullReviewCommentReaction,
  handleCreatePullReviewCommentReply,
  handleDeletePendingPullReview,
  handleDeletePullReviewComment,
  handleDeletePullReviewCommentReaction,
  handleDismissPullReview,
  handleGetPull,
  handleGetPullReview,
  handleGetPullReviewComment,
  handleGetPullText,
  handleListPullCommits,
  handleListPullFiles,
  handleListPullRequestedReviewers,
  handleListPullReviewCommentReactions,
  handleListPullReviewComments,
  handleListPullReviewCommentsForReview,
  handleListPullReviews,
  handleListPulls,
  handleListRepoPullReviewComments,
  handleMergePull,
  handleRemovePullRequestedReviewers,
  handleRequestPullReviewers,
  handleSubmitPullReview,
  handleUpdatePull,
  handleUpdatePullBranch,
  handleUpdatePullReview,
  handleUpdatePullReviewComment,
} from './pulls.js';
export { handleCreateRelease, handleCreateReleaseReaction, handleDeleteRelease, handleDeleteReleaseAsset, handleDeleteReleaseReaction, handleDownloadReleaseAsset, handleDownloadReleaseAssetByName, handleGenerateReleaseNotes, handleGetLatestRelease, handleGetReleaseAsset, handleGetReleaseById, handleGetReleaseByTag, handleListReleaseAssets, handleListReleaseReactions, handleListReleases, handleUpdateRelease, handleUpdateReleaseAsset, handleUploadReleaseAsset } from './releases.js';
export {
  handleCheckAutomatedSecurityFixes,
  handleCheckImmutableReleases,
  handleCheckVulnerabilityAlerts,
  handleCreateAutolink,
  handleCreateDeployKey,
  handleCreateRepositoryAttestation,
  handleCreateRepositoryDispatch,
  handleCreateRepositoryRuleset,
  handleDeleteAutolink,
  handleDeleteDeployKey,
  handleDeleteInteractionLimit,
  handleDeleteRepositoryRuleset,
  handleDisableAutomatedSecurityFixes,
  handleDisableImmutableReleases,
  handleDisablePrivateVulnerabilityReporting,
  handleDisableVulnerabilityAlerts,
  handleEnableAutomatedSecurityFixes,
  handleEnableImmutableReleases,
  handleEnablePrivateVulnerabilityReporting,
  handleEnableVulnerabilityAlerts,
  handleGetAutolink,
  handleGetDeployKey,
  handleGetInteractionLimit,
  handleGetPrivateVulnerabilityReporting,
  handleGetRepositoryCustomProperties,
  handleGetRepositoryHashAlgorithm,
  handleGetRepositoryRuleset,
  handleGetRepositoryRulesetVersion,
  handleGetRepositoryRuleSuite,
  handleGetRulesForBranch,
  handleListAutolinks,
  handleListCodeownersErrors,
  handleListDeployKeys,
  handleListRepositoryAttestations,
  handleListRepositoryIssueTypes,
  handleListRepositoryRulesetHistory,
  handleListRepositoryRulesets,
  handleListRepositoryRuleSuites,
  handleSetInteractionLimit,
  handleUpdateRepositoryCustomProperties,
  handleUpdateRepositoryRuleset,
} from './repo-metadata.js';
export { handleBulkDeleteUserAttestations, handleBulkListUserAttestations, handleDeleteUserAttestationById, handleDeleteUserAttestationsBySubjectDigest, handleListUserAttestations } from './user-attestations.js';
export { collectVisibleUserDids, handleGetAuthenticatedUser, handleGetUser, handleGetUserById, handleGetUserHovercard, handleListUsers, handleUpdateAuthenticatedUser } from './users.js';
export { handleSearchCode, handleSearchCommits, handleSearchIssues, handleSearchLabels, handleSearchRepositories, handleSearchTopics, handleSearchUsers } from './search.js';
export { handleGetApiVersions, handleGetEmojis, handleGetGitignoreTemplate, handleGetLicense as handleGetLicenseTemplate, handleGetMeta, handleGetRateLimit, handleGetZen, handleGitHubApiRoot, handleListGitignoreTemplates, handleListLicenses, handleRenderMarkdown, handleRenderRawMarkdown } from './meta.js';
export { handleCheckStarredRepo, handleDeleteRepoSubscription, handleGetRepoSubscription, handleListStargazers, handleListStarredRepos, handleListSubscribers, handleListSubscriptions, handleSetRepoSubscription, handleStarRepo, handleUnstarRepo } from './stars.js';
export {
  handleCreateOrgWebhook,
  handleCreateRepoWebhook,
  handleDeleteOrgWebhook,
  handleDeleteRepoWebhook,
  handleGetOrgWebhook,
  handleGetOrgWebhookConfig,
  handleGetOrgWebhookDelivery,
  handleGetRepoWebhook,
  handleGetRepoWebhookConfig,
  handleGetRepoWebhookDelivery,
  handleListOrgWebhookDeliveries,
  handleListOrgWebhooks,
  handleListRepoWebhookDeliveries,
  handleListRepoWebhooks,
  handlePingOrgWebhook,
  handlePingRepoWebhook,
  handleRedeliverOrgWebhookDelivery,
  handleRedeliverRepoWebhookDelivery,
  handleTestRepoWebhook,
  handleUpdateOrgWebhook,
  handleUpdateOrgWebhookConfig,
  handleUpdateRepoWebhook,
  handleUpdateRepoWebhookConfig,
} from './webhooks.js';
export { handleDeleteNotificationThread, handleDeleteNotificationThreadSubscription, handleGetNotificationThread, handleGetNotificationThreadSubscription, handleListNotifications, handleListRepoNotifications, handleMarkNotificationThreadRead, handleMarkNotificationsRead, handleMarkRepoNotificationsRead, handleSetNotificationThreadSubscription } from './notifications.js';
export { handleCreateCheckRun, handleCreateCheckSuite, handleCreateCommitStatus, handleGetCheckRun, handleGetCheckSuite, handleGetCombinedStatus, handleListCheckRunAnnotations, handleListCheckRunsForRef, handleListCheckRunsForSuite, handleListCheckSuitesForRef, handleListCommitStatuses, handleRerequestCheckRun, handleRerequestCheckSuite, handleUpdateCheckRun } from './checks.js';

export {
  handleAddStatusCheckContexts,
  handleDeleteBranchProtection,
  handleDeletePullRequestReviewProtection,
  handleDeleteRequiredStatusChecksProtection,
  handleGetBranch,
  handleGetBranchProtection,
  handleGetGitRef,
  handleGetPullRequestReviewProtection,
  handleGetRequiredStatusChecksProtection,
  handleListBranches,
  handleListMatchingGitRefs,
  handleListStatusCheckContexts,
  handleListTags,
  handleRemoveStatusCheckContexts,
  handleSetStatusCheckContexts,
  handleUpdateBranchProtection,
  handleUpdatePullRequestReviewProtection,
  handleUpdateRequiredStatusChecksProtection,
} from './git-refs.js';
export {
  handleCompareCommitText,
  handleCreateGitBlob,
  handleCreateGitCommit,
  handleCreateGitRef,
  handleCreateGitTag,
  handleCreateGitTree,
  handleDeleteGitContents,
  handleDeleteGitRef,
  handleDownloadArchive,
  handleGetGitTag,
  handleGetRepoCommitMedia,
  handleListContributors,
  handleListRepoCommits,
  handlePutGitContents,
  handleUpdateGitRef,
  tryGetGitRawContent,
} from './git-objects.js';
export {
  buildApiUrl,
  buildLinkHeader,
  buildOwner,
  findByShortId,
  fromOpt,
  getRepoRecord,
  numericId,
  paginate,
  parsePagination,
  shortId,
  toISODate,
} from './helpers.js';

export type {
  GitHubOwner,
  JsonResponse,
  PaginationParams,
  RepoInfo,
} from './helpers.js';
